# Generated by Django 2.2 on 2019-04-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, null=True, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=20, null=True, verbose_name='Фамилия')),
                ('address', models.TextField(null=True, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Телефон')),
                ('birthday', models.DateField(null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(max_length=1, null=True, verbose_name='Пол')),
                ('updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата обновления')),
            ],
        ),
    ]
