# Generated by Django 2.2 on 2021-04-08 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_datatable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Название профессии')),
            ],
        ),
        migrations.CreateModel(
            name='StudyDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='Направление обучения')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=20, null=True, verbose_name='Фамилия')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50, verbose_name='Пол')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Адрес участка')),
                ('organization_type', models.CharField(choices=[('Правительственная', 'Правительственная'), ('Неправительственная', 'Неправительственная'), ('Коммерческая', 'Коммерческая'), ('Некоммерческая', 'некоммерческая'), ('Бюджетная', 'Бюджетная'), ('Внебюджетная', 'Внебюджетная'), ('Общественные', 'Общественные'), ('Хозяйственные', 'Хозяйственные')], max_length=20, verbose_name='Тип организации')),
                ('organization_name', models.CharField(max_length=30, null=True, verbose_name='Имя организации')),
                ('appointment', models.CharField(max_length=30, null=True, verbose_name='Должность')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Profession')),
            ],
        ),
        migrations.AddField(
            model_name='profession',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.StudyDirection'),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=40, null=True, verbose_name='Образовательное учреждение')),
                ('address', models.CharField(max_length=60, null=True, verbose_name='Адрес')),
                ('foundation_date', models.DateField()),
                ('image', models.ImageField(upload_to='photos')),
                ('professions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Profession')),
            ],
        ),
    ]
